### ISSUE TITLE
Handling users and certificates with cockroach operator

### ISSUE THREAD

**Issue by simonebenati** [cockroachdb/cockroach-operator#1000]
- Is your feature request related to a problem? Please describe.

The issue I'm having is generating new db users and creating the relative certificates and then distributing them. with self hosted cockroachdb

- Describe the solution you'd like

A CR to handle users and authentication kind: CrdbUser (?)

- Describe alternatives you've considered

Better explanation with the current tools on how to handle the creation and then the distribution of certificates at large scale.

- Additional context

At the moment the things I do to generate a certificate with the cockroachdb self signed ca are:

create a crdb-client-secure pod with the following piece added:
```
          - secret:
              name: cockroachdb-root
              items:
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
                - key: ca.crt
                  path: ca.crt
```
ca.crt is taken from the cockroachdb-root secret

1. login as root, create user xyz, grant permission
2. create a folder 'certs'
3. create the certs via cockroach certs
4. cat of each cert created and saving it on my machine to distribute them
This feels super weird to do and I extensively read the documentation but haven't found any better way. This isn't in the documentation aswell and I came up with this after many attempts.
