### ISSUE TITLE
Difference between Kubernetes Operator Secure Cluster Behavior and Our Docs

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#101]
Using the [3-nodes-secure-kube-cert.yaml](https://github.com/cockroachdb/cockroach-operator/blob/master/config/examples/3-nodes-secure-kube-cert.yaml), it appeared to fail to create a secure cluster.

**Repro Steps**
After following the deployment instructions in the README:
1. ./hack/create-gke-cluster.sh -c $CLUSTER
2. ./hack/push-operator-gcr.sh
3. ./hack/apply-operator.sh -c $CLUSTER

I applied the [3-nodes-secure-kube-cert.yaml](https://github.com/cockroachdb/cockroach-operator/blob/master/config/examples/3-nodes-secure-kube-cert.yaml).

**Expected Results**
Based on our [Secure/CockroachDB/Kubernetes Wiki guidance](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html), I expect to see a csr for each CockroachDB node.

**Actual Results**
It successfully installed and had pods running with the correct version of CockroachDB. However, when running "kubectl get csr," it didn't show any csr. 

**Environment**
I tested both on my GCP dev server following these [instructions](https://github.com/chrislovecnm/gcp-dev-server-terraform) and on my local laptop.

**Comment by chrislovecnm** [comment]
I am not able to recreate this issue.  I followed the following steps on the master branch.

```bash
kubectl create -f config/examples/3-nodes-secure-kube-cert.yaml
```

The cluster created. And here is the node CSR.

```bash
$ k describe csr node.crdb-secure-pvc.default.svc.cluster.local
Name:               node.crdb-secure-pvc.default.svc.cluster.local
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Wed, 22 Jul 2020 16:54:50 +0000
Requesting User:    system:serviceaccount:default:cockroach-operator-default
Status:             Approved,Issued
Subject:
  Common Name:    node
  Serial Number:
  Organization:   Cockroach Labs
Subject Alternative Names:
         DNS Names:     localhost
                        crdb-secure-pvc-public
                        crdb-secure-pvc-public.default
                        crdb-secure-pvc-public.default.svc.cluster.local
                        *.crdb-secure-pvc
                        *.crdb-secure-pvc.default
                        *.crdb-secure-pvc.default.svc.cluster.local
         IP Addresses:  127.0.0.1
Events:  <none>
```

Here is the root csr:

```bash
Name:               root.crdb-secure-pvc.default.svc.cluster.local
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Wed, 22 Jul 2020 16:55:02 +0000
Requesting User:    system:serviceaccount:default:cockroach-operator-default
Status:             Approved,Issued
Subject:
         Common Name:    root
         Serial Number:
         Organization:   Cockroach Labs
Events:  <none>
```

The database is running in secure mode.

```yaml
spec:
  containers:
  - args:
    - shell
    - -ecx
    - '>- exec /cockroach/cockroach start --join=crdb-secure-pvc-0.crdb-secure-pvc.default:26257,crdb-secure-pvc-1.crdb-secure-pvc.default:26257,crdb-secure-pvc-2.crdb-secure-pvc.default:26257
      --advertise-host=$(hostname -f) --logtostderr=INFO --certs-dir=/cockroach/cockroach-certs/
      --http-port=8080 --port=26257 --cache=25% --max-sql-memory=25%'
```

@chrisseto correct me if I am wrong, but when you start crdb without the `--insecure` flag and set  `--certs-dir` flag, CRDB is running in secure mode.  I believe that the pod would not start if the certificates were not correct.

Now we are not creating a client cert or the admin UI cert, which I think we probably need to create as well.  I will open a ticket in order to discuss that requirement.  I'm trying to figure out if I can get the secure client example to work.

**Comment by chrislovecnm** [comment]
Talking with @chrisseto he gave me this command to confirm:

```bash
$ k exec -it crdb-secure-pvc-0 -- /bin/bash
root@crdb-secure-pvc-0:/cockroach# ./cockroach --certs-dir /cockroach/cockroach-certs/ sql
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v19.2.6 (x86_64-unknown-linux-gnu, built 2020/04/06 18:05:31, go1.12.12) (same version as client)
# Cluster ID: bae3eade-d7a0-4ea4-a5f7-82f96f444192
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> SELECT * FROM crdb_internal.node_runtime_info WHERE field = 'URI';
  node_id | component | field |                                                                                           value
+---------+-----------+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
        1 | DB        | URI   | /?sslcert=%2Fcockroach%2Fcockroach-certs%2Fclient.root.crt&sslkey=%2Fcockroach%2Fcockroach-certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=%2Fcockroach%2Fcockroach-certs%2Fca.crt
        1 | UI        | URI   | /
(2 rows)

Time: 1.00271ms
```

**Comment by chrislovecnm** [comment]
I actually got the secure client example to work as well. I had to modify the yaml to use the operator service account.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
  labels:
    app: cockroachdb-client
spec:
  serviceAccountName: cockroach-operator-default
  initContainers:
  # The init-certs container sends a certificate signing request to the
  # kubernetes cluster.
  # You can see pending requests using: kubectl get csr
  # CSRs can be approved using:         kubectl certificate approve <csr name>
  #
  # In addition to the client certificate and key, the init-certs entrypoint will symlink
  # the cluster CA to the certs directory.
  - name: init-certs
    image: cockroachdb/cockroach-k8s-request-cert:0.4
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/ash"
    - "-ecx"
    - "/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=client -user=root -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
  containers:
  - name: cockroachdb-client
    image: cockroachdb/cockroach:v20.1.3
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
    # Keep a pod open indefinitely so kubectl exec can be used to get a shell to it
    # and run cockroach client commands, such as cockroach sql, cockroach node status, etc.
    command:
    - sleep
    - "2147483648" # 2^31
  # This pod isn't doing anything important, so don't bother waiting to terminate it.
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    emptyDir: {}
```

That pod will not start fully until you approve the certificate:

```bash
$ kubectl certificate approve default.client.root
```

Then exec into the pod

```bash
kubectl exec -it cockroachdb-client-secure -- /bin/bash
```

And run the `coachroach` command to connect to the database:

```bash
root@cockroachdb-client-secure:/cockroach# ./cockroach sql --certs-dir=/cockroach-certs --host=crdb-secure-pvc-public
```

This logs you into the database. You can confirm which hosts you are connected to by running:

```bash
root@crdb-secure-pvc-public:26257/defaultdb> select args from crdb_internal.kv_node_status;
                                                                                                                                                                                                           args
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  ["/cockroach/cockroach", "start", "--join=crdb-secure-pvc-0.crdb-secure-pvc.default:26257,crdb-secure-pvc-1.crdb-secure-pvc.default:26257,crdb-secure-pvc-2.crdb-secure-pvc.default:26257", "--advertise-host=crdb-secure-pvc-0.crdb-secure-pvc.default.svc.cluster.local", "--logtostderr=INFO", "--certs-dir=/cockroach/cockroach-certs/", "--http-port=8080", "--port=26257", "--cache=25%", "--max-sql-memory=25%"]
  ["/cockroach/cockroach", "start", "--join=crdb-secure-pvc-0.crdb-secure-pvc.default:26257,crdb-secure-pvc-1.crdb-secure-pvc.default:26257,crdb-secure-pvc-2.crdb-secure-pvc.default:26257", "--advertise-host=crdb-secure-pvc-1.crdb-secure-pvc.default.svc.cluster.local", "--logtostderr=INFO", "--certs-dir=/cockroach/cockroach-certs/", "--http-port=8080", "--port=26257", "--cache=25%", "--max-sql-memory=25%"]
  ["/cockroach/cockroach", "start", "--join=crdb-secure-pvc-0.crdb-secure-pvc.default:26257,crdb-secure-pvc-1.crdb-secure-pvc.default:26257,crdb-secure-pvc-2.crdb-secure-pvc.default:26257", "--advertise-host=crdb-secure-pvc-2.crdb-secure-pvc.default.svc.cluster.local", "--logtostderr=INFO", "--certs-dir=/cockroach/cockroach-certs/", "--http-port=8080", "--port=26257", "--cache=25%", "--max-sql-memory=25%"]
(3 rows)

Time: 6.063026ms
```

So yes the database is running with TLS certs enables, but not we are not generating a client cert automatically, but you can generate them with this example or maybe we should create a client certificate.
