### ISSUE TITLE
Using ingress with operator

### ISSUE THREAD

**Issue by himanshusaini-fa** [cockroachdb/cockroach-operator#1014]
I am trying to set up public access to a cluster deployed using the operator. I am using the below configuration while deploying a CrdbCluster.

```yaml
  ingress:
    ui:
      ingressClassName: nginx
      host: cockroach.cooldb.xyz
 ```
 
 I am using nginx controller and cert-manager.
 
 Below is my ingress and cert manager in order
 
 ```yaml
 apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cockroach-ingress
  namespace: cockroach-operator-system
  annotations:
    cert-manager.io/cluster-issuer: cert-issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx 
  tls:
    - hosts:
        - cockroach.cooldb.xyz
      secretName: letsencrypt-cert
  rules:
    - host: cockroach.cooldb.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cockroachdb-public
                port:
                  name: http
```

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: user@cooldb.xyz
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-cluster-issuer
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    # https://github.com/Mimetis/AKS_DNS01Solver/tree/master
      - dns01:
          azureDNS:
            clientID: #############################
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            subscriptionID: ###########################
            tenantID: ##############################
            resourceGroupName: cool-domains
            hostedZoneName: cooldb.xyz
            environment: AzurePublicCloud
```

But I am still getting error ERR_TOO_MANY_REDIRECTS in the browser while trying to acces the db at the domain cockroach.cooldb.xyz and also getting 307 logs from nginx-controller hitting the correct service "cockroachdb-public".

What am I doing wrong here?
