### ISSUE TITLE
working use case (tanzu): vCenter 8 / esxi 8 / v1.26.5+vmware.2-fips.1

### ISSUE THREAD

**Issue by lknite** [cockroachdb/cockroach-operator#1030]
So far everything seems to be working.

Worked after adding the following labels to the ```cockroach-operator-system``` namespace:
```
          labels:
            pod-security.kubernetes.io/enforce: privileged # baseline
            pod-security.kubernetes.io/audit: restricted
            pod-security.kubernetes.io/warn: baseline # privileged
```
