### ISSUE TITLE
Specifying priorityClassName for database pods

### ISSUE THREAD

**Issue by mohsenasm** [cockroachdb/cockroach-operator#1103]
Hi,

Is there a way to configure the [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) for the database statefulset pods?

---

If it's not implemented yet, maybe we can specify the config like:

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  priorityClassName: "a-priority-class-name"
```

And apply the config here:

https://github.com/cockroachdb/cockroach-operator/blob/d1ab85c6b3f6c670f3a8d4a6410aafc75c262e6e/pkg/resource/statefulset.go#L207-L216

I can also open a PR.
Thanks.
