### ISSUE TITLE
PDB issue: minor version change occurred, minAvailable and nodes were the same

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#135]
**Test Case**
With number of nodes (3) and number of minAvailable nodes (3) were the same, I attempted to change minor version from v20.1.3 to v20.1.2.

**Expectd Outcome:** 
I expected K8s to not permit this minor version change because I declared for the minAvailable number of nodes to be 3. 

**Actual Outcome:**
With this configuration, it allowed for less than 3 nodes to be available.

**Full Config:**
```
piVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-secure-pvc-3
spec:
  tlsEnabled: true
  # trying to figure out what this does
  # nodeTLSSecret: GENERATED
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        # this needs to be precreated
        # storageClassName: crdb-io1
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.1.2
    # pullPolicy: Always
    # pullPolicySecret: mySecretName
    # ^ some secret in kubernetes, 
  nodes: 3
  minAvailable: 3
```
