### ISSUE TITLE
pod creation failing

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach-operator#160]
running: `us.gcr.io/rk-k8s-test/cockroach-operator:ee5482e`

Applied the following config:

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
          storage: 240Gi
        volumeMode: Filesystem
  tlsEnabled: true
  # nodeTLSSecret: cockroachdb.node
  # clientTLSSecret: cockroachdb.client.root
  image:
    name: cockroachdb/cockroach:v20.1.4
  nodes: 3
```

Pods didn't create. Events log showed:

```3m41s       Warning   FailedCreate                      statefulset/cockroachdb                        create Claim datadir-cockroachdb-0 for Pod cockroachdb-0 in StatefulSet cockroachdb failed error: PersistentVolumeClaim "datadir-cockroachdb-0" is invalid: spec.resources[storage]: Required value
3m51s       Warning   FailedCreate                      statefulset/cockroachdb                        create Pod cockroachdb-0 in StatefulSet cockroachdb failed error: failed to create PVC datadir-cockroachdb-0: PersistentVolumeClaim "datadir-cockroachdb-0" is invalid: spec.resources[storage]: Required value
2m58s       Normal    NoPods                            poddisruptionbudget/cockroachdb                No matching pods found
28s         Normal    NoPods                            poddisruptionbudget/cockroachdb                No matching pods found
2m17s       Warning   FailedCreate                      statefulset/cockroachdb                        create Claim datadir-cockroachdb-0 for Pod cockroachdb-0 in StatefulSet cockroachdb failed error: PersistentVolumeClaim "datadir-cockroachdb-0" is invalid: spec.resources[storage]: Required value
2m27s       Warning   FailedCreate                      statefulset/cockroachdb                        create Pod cockroachdb-0 in StatefulSet cockroachdb failed error: failed to create PVC datadir-cockroachdb-0: PersistentVolumeClaim "datadir-cockroachdb-0" is invalid: spec.resources[storage]: Required value```
