### ISSUE TITLE
Test if lack of volumeMode breaks operator

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#181]
```
diff --git a/examples/example.yaml b/examples/example.yaml
index 8bfc269..9a1d6b5 100644
--- a/examples/example.yaml
+++ b/examples/example.yaml
@@ -24,8 +24,9 @@ spec:
         - ReadWriteOnce
         resources:
           requests:
-            storage: 60Gi
+            storage: 60Gi
+        volumeMode: Filesystem
   tlsEnabled: true
   image:
-    name: cockroachdb/cockroach:v20.1.3
+    name: cockroachdb/cockroach:v20.1.6
   nodes: 3
```
vs

```yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-example
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        volumeMode: Filesystem
  tlsEnabled: true
  image:
    name: cockroachdb/cockroach:v20.1.6
  nodes: 3
```

The first code block is a diff from the second code block. I had an issue where the operator would run into a race condition maybe if the `volumeMode` was left off of the dataSource block.  We need to investigate more.
