### ISSUE TITLE
Tanzu - CRDB Operator doesn't provide a way to assign annotations to the PVC used by the created pods

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach-operator#213]
When you create PVCs that need to bind to PVs in Tanzu, you need to specify which storageClass to use.  For some reason, Tanzu doesn't want that storageClassName specified in the pvc.spec; instead it wants it specified as an annotation in the pvc.metadata.annotations like this:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-disk-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: example-thin-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

When specifying the CrdbCluster manifest file, I don't think there's a way to specify the annotations for the PVC.

I think it would make sense to have an object something like this:
```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-example
spec:
  dataStore:
    pvc:
      #BEGIN JIM making up a suggested interface
      metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: example-thin-disk
      #END JIM making up a suggested interface
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        volumeMode: Filesystem
  tlsEnabled: true
  image:
    name: cockroachdb/cockroach:v20.1.6
  nodes: 3
```

Or maybe we could intercept values provided in the CrdbCluster.spec.pvc.spec.storageClassName and if we're running in Tanzu, push those to the PVC annotations?

**Comment by chrislovecnm** [comment]
Did you name the storage class in the CR?

**Comment by jhatcher9999** [comment]
yeah, I tried putting the storage class name in like this:

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-example
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        storageClassName: example-thin-disk
        volumeMode: Filesystem
  tlsEnabled: true
  image:
    name: cockroachdb/cockroach:v20.1.6
  nodes: 3
```

But, the PVC would show as having no storageClassName assigned if you looked at it with `kubectl get pvc`

I even tried deleting the PVC and recreating it in different ways.  If I specified the storageClassName in the annotation, it would work; otherwise it just got ignored.
