### ISSUE TITLE
Address Permissions Required by the Operator

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#258]
We need to constrain the permissions needed by the operator (currently needs all the privileges). 
For example:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cockroach-operator-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
```

**Comment by keith-mcclellan** [comment]
@chrislovecnm this is our top priority bug after we are feature complete on the operator :-)

**Comment by keith-mcclellan** [comment]
@alinadonisa this is your top priority as soon as empty-dir is complete. Thanks!

**Comment by keith-mcclellan** [comment]
Here's how we fixed the cert permissions issue in other install patterns

```
      initContainers:
        - name: permfix
          image: 'busybox:1.28'
          command:
            - sh
            - '-c'
            - >-
              cp -p /cockroach/cockroach-certs-prestage/..data/*
              /cockroach/cockroach-certs/ && chmod 700
              /cockroach/cockroach-certs/*.key
          resources: {}
          volumeMounts:
            - name: certs
              mountPath: /cockroach/cockroach-certs-prestage
            - name: emptydir
              mountPath: /cockroach/cockroach-certs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
```
