### ISSUE TITLE
new deployment on google cloud dumps TLS handshake errors 

### ISSUE THREAD

**Issue by mgenov** [cockroachdb/cockroach-operator#277]
I got a new deployment of cockroachdb using cockroach-operator with the following configuration:

```yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  tlsEnabled: true  
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi        
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3

```

and server is up and running but the pods logs are continusly showing errors like this:

```
E210108 09:12:13.337166 4999 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:60814: remote error: tls: bad certificate
E210108 09:12:18.319390 5125 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:60988: remote error: tls: bad certificate
I210108 09:12:19.614459 233 server/status/runtime.go:522 ⋮ [n2] runtime stats: 218 MiB RSS, 224 goroutines, 30 MiB/90 MiB/58 MiB GO alloc/idle/total, 47 MiB/64 MiB CGO alloc/total, 0.1 CGO/sec, 4.2/1.0 %(u/s)time, 0.0 %gc (1x), 211 KiB/201 KiB (r/w)net
E210108 09:12:23.314892 5206 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:32938: remote error: tls: bad certificate
E210108 09:12:28.315608 5315 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:33128: remote error: tls: bad certificate
```
