### ISSUE TITLE
Bug: TLS: Bad Certificate Error from Operator

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#280]
Two people from our community found the Operator to result in this error when running: **E210108 09:12:13.337166 4999 (gostd) net/http/server.go:3083  `http: TLS handshake error from 10.24.2.23:60814: remote error: tls: bad certificate`**

**Full Message:**
Hi guys I’m trying out cockroachdb deployment on k8s with the cockroachdb operator with the following configuration:
apiVersion: crdb.cockroachlabs.com/v1alpha1
```
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  tlsEnabled: true  
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi        
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3
```
But the pod logs are showing continously the following errors:
E210108 09:12:13.337166 4999 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:60814: remote error: tls: bad certificate
E210108 09:12:18.319390 5125 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:60988: remote error: tls: bad certificate
I210108 09:12:19.614459 233 server/status/runtime.go:522 ⋮ [n2] runtime stats: 218 MiB RSS, 224 goroutines, 30 MiB/90 MiB/58 MiB GO alloc/idle/total, 47 MiB/64 MiB CGO alloc/total, 0.1 CGO/sec, 4.2/1.0 %(u/s)time, 0.0 %gc (1x), 211 KiB/201 KiB (r/w)net
E210108 09:12:23.314892 5206 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:32938: remote error: tls: bad certificate
E210108 09:12:28.315608 5315 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:33128: remote error: tls: bad certificate
Is this normal or I’m missing something?

**Comment by mgenov** [comment]
Here are the reproduction steps from my side:

Step 1
```
kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml

kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml

```

Step 2 

Create cluster definition: cockroachdb.yaml
```
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  tlsEnabled: true  
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi        
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3
```

Step 3:
```
kubectl create -f cockroachdb.yaml
```

Step 4:
```
kubectl logs -f cockroachdb-0
```

shows continuously the following messages:
```
E210111 16:02:29.712520 8182705 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:48714: remote error: tls: bad certificate
I210111 16:02:33.813885 241 server/status/runtime.go:522 ⋮ [n1] runtime stats: 1.5 GiB RSS, 240 goroutines, 151 MiB/722 MiB/270 MiB GO alloc/idle/total, 458 MiB/577 MiB CGO alloc/total, 0.1 CGO/sec, 4.9/1.2 %(u/s)time, 0.0 %gc (0x), 182 KiB/254 KiB (r/w)net
E210111 16:02:34.713310 8182857 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:48884: remote error: tls: bad certificate
E210111 16:02:39.712608 8183013 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:49058: remote error: tls: bad certificate
I210111 16:02:43.814032 241 server/status/runtime.go:522 ⋮ [n1] runtime stats: 1.5 GiB RSS, 240 goroutines, 165 MiB/712 MiB/270 MiB GO alloc/idle/total, 458 MiB/577 MiB CGO alloc/total, 0.1 CGO/sec, 5.1/0.9 %(u/s)time, 0.0 %gc (0x), 179 KiB/248 KiB (r/w)net
E210111 16:02:44.711121 8183136 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:49222: remote error: tls: bad certificate
E210111 16:02:49.713680 8183264 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:49402: remote error: tls: bad certificate
I210111 16:02:53.819733 241 server/status/runtime.go:522 ⋮ [n1] runtime stats: 1.5 GiB RSS, 240 goroutines, 180 MiB/700 MiB/270 MiB GO alloc/idle/total, 458 MiB/577 MiB CGO alloc/total, 0.1 CGO/sec, 5.2/1.0 %(u/s)time, 0.0 %gc (0x), 190 KiB/263 KiB (r/w)net
E210111 16:02:54.712098 8183448 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:49566: remote error: tls: bad certificate
E210111 16:02:59.713712 8183576 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:49740: remote error: tls: bad certificate

```

**Comment by chrislovecnm** [comment]
@mgenov where were you deploying this to?  GKE?
cc @keith-mcclellan

**Comment by mgenov** [comment]
Yes, cluster is deployed on GKE.

**Comment by keith-mcclellan** [comment]
Did you previously have a different crdb cluster deployed by the operator with the same name in metadata.name?

**Comment by mgenov** [comment]
Not sure about that but think that I haven't changed any name. I have an
empty cluster now, so I can rebuild everything from scratch.

Can you guide me about the steps that I need to take? (including cleanup of
existing cluster)

**Comment by mgenov** [comment]
Tried with:

```
kubectl delete -f releases/db/cockroachdb.yaml
kubectl delete pv,pvc --all
kubectl delete -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml
```

Also deleted all csr requests, re-deployed the cluster again and the error still remains. 
```
E210215 15:13:58.854571 4239242 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.24.2.23:36164: remote error: tls: bad certificate
```

Any ideas?

**Comment by chrislovecnm** [comment]
kubectl version 

can I get the output of that please

**Comment by mgenov** [comment]
Sure.

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by chrislovecnm** [comment]
So first I need you to downgrade kubectl. You should never use a version higher than one major ahead. I will test out the version in a bit myself.

**Comment by chrislovecnm** [comment]
So I am able to create both the example and your example as well.

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1600", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-07T09:22:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

Let me upgrade GKE.

**Comment by chrislovecnm** [comment]
Some comments on your CR.

```yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1 # you missed this field
kind: CrdbCluster
metadata:
  name: cockroachdb-test
spec:
  tlsEnabled: true
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard # you do not need this, it defaults to the default in the cluster
        volumeMode: Filesystem # you do not need this, as Filesystem is the default
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3
```

**Comment by mgenov** [comment]
It seems missed during copy/paste in the issue. Here is the complete configuration:

```yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  tlsEnabled: true
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.4
  nodes: 3
```

**Comment by mgenov** [comment]
Just saw the volumeMode and storageClassName. Will remove them from the config. Do I have to re-created cluster after this change or I can check the existing one?

**Comment by mgenov** [comment]
btw, version in current config is 20.2.4 but the issue is same for 20.2.3 and 20.2.4.

**Comment by chrislovecnm** [comment]
So I am unable to recreate the issue.  I am using a newer version of GKE, and I would recommend you upgrading.  

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.15-gke.800", GitCommit:"2e625a55a420ded12d04226c63c4cf415efc9cdb", GitTreeState:"clean", BuildDate:"2021-01-25T09:17:48Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

Here is what I did

```console
$  hack/create-gke-cluster.sh -c test
```

Wait for the cluster to come up.  This is a pretty vanilla cluster.

```console
kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml
```

Wait for the operator to come up

```console
$ kubectl create -f examples/example.yaml
```
I created the example first to ensure that our example worked. Wait for it to come up, and it works.

```console
$ kubectl create -f test.yaml
```

The contents of the YAML are below.  Note that I did change the name of the cluster.  We have an open issue where the secrets are not cleaned up and maybe it is grabbing that?  Not certain.

```yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb-test
spec:
  tlsEnabled: true
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3
```

I am trying just to create the one cluster.

**Comment by mgenov** [comment]
Thanks. I will give it a try. Can you point me to the secrets location to look for to see whether the problem is related to an old secrets?

**Comment by mgenov** [comment]
This is what I have in the default namespace related to cockroachdb:
```
NAME                                TYPE                                  DATA   AGE
cockroach-operator-sa-token-wm9vz   kubernetes.io/service-account-token   3      2d6h
cockroachdb-node                    Opaque                                3      2d6h
cockroachdb-root                    Opaque                                3      2d6h
istio.cockroach-operator-sa         istio.io/key-and-cert                 3      2d6h
```

Could the problem be related to the fact that istio is deployed in the cluster?

**Comment by chrislovecnm** [comment]
> Could the problem be related to the fact that istio is deployed in the cluster?

Not tested as of yet

**Comment by chrislovecnm** [comment]
```
cockroachdb-node
```
That is the old secret, but I am thinking that is not the problem.  I might be istio, will test that.

**Comment by chrislovecnm** [comment]
This works

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb-test2
spec:
  tlsEnabled: true
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3
```

Testing with istio.

**Comment by chrislovecnm** [comment]
Yep, it is istio.

**Comment by chrislovecnm** [comment]
@mgenov I am wondering if we install the certificates by hand if it works.

**Comment by mgenov** [comment]
I can give it a try. Can you show me a guide or steps to follow?

**Comment by chrislovecnm** [comment]
I just upgraded my cluster and installed istio and I am getting the error you found.

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb-test3
spec:
  tlsEnabled: true
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3
```

**Comment by chrislovecnm** [comment]
```
$ k logs -f cockroachdb-test3-2 | grep TLS
E210215 17:52:39.436698 7583 (gostd) net/http/server.go:3083  http: TLS handshake error from 10.56.0.15:33768: remote error: tls: bad certificate
```

```
$ k describe pods cockroachdb-test3-2 | grep IP
Annotations:  cni.projectcalico.org/podIP: 10.56.1.15/32
IP:           10.56.1.15
```

It is having a problem talking to itself?

@keith-mcclellan @chrisseto need some assistance with this one.  So when we add istio to a cluster we are having a handshake issue back to the pod itself.  Thoughts?

**Comment by chrislovecnm** [comment]
Here are the steps that I used to recreate
1. used create-cluster.sh to create the cluster
2. went into the console and added istio
3. installed the operator
4. used the test yaml file

The cluster seems up, but we are getting errors in the logs.

```yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb-test3
spec:
  tlsEnabled: true
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: standard
        volumeMode: Filesystem
  image:
    name: cockroachdb/cockroach:v20.2.3
  nodes: 3
```

See https://github.com/cockroachdb/cockroach-operator/issues/280#issuecomment-779375080 for the errors.

I deleted the cluster and created a new cluster without Istio, and we are not getting the errors.
