### ISSUE TITLE
Update operator so it doesn't rely on PID 0

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#306]
The operator is still launching cockroachdb container processes as PID 0 - this needs to be fixed.  This update should also allow us to move away from:

```
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: cockroach-database-sa
```

to:

```
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - nonroot
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: cockroach-database-sa
``` 

In the openshift CSV
