### ISSUE TITLE
extend CRD to allow location aware setups

### ISSUE THREAD

**Issue by arminfelder** [cockroachdb/cockroach-operator#321]
I suggest adding --location argument, and pass it the k8s node name, to prevent suboptimal distribution of replicas inside a cluster

e.g.:

```yaml 
...
   - args:
      - start
      - ...
      - --location=k8s-node=${NODE_NAME},property=value,...  
   - env:
       - name: NODE_NAME
         valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```
