### ISSUE TITLE
add nodeAntiaffinities

### ISSUE THREAD

**Issue by arminfelder** [cockroachdb/cockroach-operator#322]
all cockroach nodes should run with "preferredDuringSchedulingIgnoredDuringExecution"

e.g.

```yaml
...
 affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
```
