### ISSUE TITLE
Operator example.yaml has incorrect indentation

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach-operator#463]
During the bug bash, we found that the `example.yaml` file had the hardware resource limits at the same level as `pvc`. This should instead be aligned with `dataStore` to avoid causing issues when the lines are uncommented.

**Comment by johnrk** [comment]
@piyush-singh , can you share a copy of the example.yaml that failed for you before and after?

**Comment by johnrk** [comment]
I suspect it has to do with the commenting/uncommenting confusion with spacing

**Comment by piyush-singh** [comment]
This is the version that worked:

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "10Gi"
        volumeMode: Filesystem
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
  tlsEnabled: true
  # cockroachDBVersion: v20.2.8
  image:
    name: cockroachdb/cockroach:v20.2.8
  nodes: 6
```

When I download the example.yaml file, the resources were commented out and aligned differently (with pvc):
```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "60Gi"
        volumeMode: Filesystem
  # resources:
  #   requests:
  #     cpu: "2"
  #     memory: "8Gi"
  #   limits:
  #     cpu: "2"
  #     memory: "8Gi"
  tlsEnabled: true
  # cockroachDBVersion: v20.2.7
  image:
    name: cockroachdb/cockroach:v20.2.7
  nodes: 3
```

I assumed that the resources needed to stay in the same position after uncommenting which led to to the issue. Could help to have an example of a working example.yaml in the docs or to change the alignment when they are commented out.
