### ISSUE TITLE
Document setting up prometheus with an operator created cluster

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach-operator#469]
I've created an CockroachDB cluster via the operator and stumbled through settings up prometheus monitoring by following [the tutorial in the CockroachDB repo](https://github.com/cockroachdb/cockroach/tree/master/cloud/kubernetes/prometheus#monitoring).

The link to the prometheus operator manifest in the above tutorial appears to have expired. I tracked down [the bundle](https://github.com/prometheus-operator/prometheus-operator/blob/67a6f56d426ed87940af301cfd0833facd2b3af7/bundle.yaml) in the prometheus operator repo.

Everything else appears to work just fine with the exception of the `ServiceMonitor` which points at an incorrect CA.

I was able to get it working by swapping the `tlsConfig` to the below value. The config needs access to the `ca.crt` which is not present in the `cockroachdb-ca` secret so I fell back to using the `cockroachdb-node` secret. We should likely include the `ca.crt` in `cockroachdb-ca` or in a separate secret for ease of use before fully documenting this.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cockroachdb
    prometheus: cockroachdb
  name: cockroachdb
spec:
  endpoints:
  - path: /_status/vars
    port: http
    tlsConfig:
      ca:
        secret:
          key: ca.crt
          name: cockroachdb-node
      serverName: 127.0.0.1
  selector:
    matchLabels:
      prometheus: cockroachdb
```

cc @chudro
