### ISSUE TITLE
operator: failed to upgrade from 19.2.12 to 20.1.15 on n1-standard-4

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach-operator#478]
I had a 3 node `n1-standard-4` cluster with 

```yaml
       accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "60Gi"
        volumeMode: Filesystem
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
```

settings, I cannot upgrade successfully, can't tell whether it's a resource issue or something wrong with `20.1.15`. I did verify it was specified in the manifest.
