### ISSUE TITLE
can't connect to client pod after changing sqlPort

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach-operator#497]
When changing `sqlPort` from `26257` to `5432` in the custom resource, this successfully performs a rolling restart of the pods with the new SQL port. However, the client pod previously deployed with the following YAML:

```
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/name: cockroachdb
spec:
  serviceAccountName: cockroach-operator-sa
  containers:
  - name: cockroachdb-client-secure
    image: cockroachdb/cockroach:v20.2.8
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach/cockroach-certs/
    command:
    - sleep
    - "2147483648" # 2^31
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    projected:
        sources:
          - secret:
              name: cockroachdb-node
              items:
                - key: ca.crt
                  path: ca.crt
          - secret:
              name: cockroachdb-root
              items:
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
        defaultMode: 256
```

can no longer connect via SQL on the new port. When running `kubectl exec -it cockroachdb-client-secure -- ./cockroach sql --certs-dir=/cockroach/cockroach-certs --host=cockroachdb-public --port=5432`, I get the following error:

```
ERROR: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

dial tcp 10.3.242.84:5432: i/o timeout
Failed running "sql"
command terminated with exit code 1
```

Prior to changing the SQL port, I was able to connect to the same client pod on `26257`.

Connecting directly to one of the Cockroach pods does work on the new SQL port `5432`.

This is using the Operator version currently at https://github.com/cockroachdb/cockroach-operator/blob/master/manifests/operator.yaml on GKE and CRDB v20.2.8.
