### ISSUE TITLE
Add pod affinity and anti-affinity config to the API

### ISSUE THREAD

**Issue by udnay** [cockroachdb/cockroach-operator#615]
We need to add pod affinity and anti-affinity to the `CRDB` custom resource.

In the CockroachDB docs we have a sample stateful set affinity rule
```
  affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cockroachdb
              topologyKey: kubernetes.io/hostname
```

How do we want to do this as just a part of the  top level `spec` or build out something like `dataStore` to control this? Maybe this is part of a larger `placement` API or under nodes?

You could have:
```
nodes
  replicas: 3
  affinity:
     ...
```
Could later add in more things like regions? If we do this can we keep `nodes: 3` if the user doesn't want to specify any affinity rules?

Thoughts @keith-mcclellan @chrislovecnm
