### ISSUE TITLE
Creating in instance of a cluster with TLS disabled fails to start

### ISSUE THREAD

**Issue by ffapitalle** [cockroachdb/cockroach-operator#640]
Using CockroachDB Operator v2.0.1 on OCP 4.6.36, when creating a cluster instance with TLS disabled, db pods remains in `Init:CrashLoopBackOff` state.

```
NAME                     READY   STATUS                  RESTARTS   AGE
crdb-non-tls-example-0   0/1     Init:CrashLoopBackOff   7          13m
crdb-non-tls-example-1   0/1     Init:CrashLoopBackOff   7          13m
crdb-non-tls-example-2   0/1     Init:CrashLoopBackOff   7          13m
```

We are using all default values, except for `tlsEnabled` set to `false`. Full CRD is as follows

```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-non-tls-example
  namespace: sample-namespace
spec:
  cockroachDBVersion: v21.1.5
  tlsEnabled: false
  nodes: 3
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
```

After some debugging I found that the init container executes a `cp` command on a path that is not mounted as a volume (as it is in a TLS enabled cluster).

The only log available is from the `db-init` pod
```
$ oc logs crdb-non-tls-example-0 -c db-init
cp: cannot stat '/cockroach/cockroach-certs-prestage/..data/*': No such file or directory
```

```
$ oc describe pod crdb-non-tls-example-0
...
Init Containers:
  db-init:
    Container ID:  cri-o://1a75b1ee2e817c56732c99ff08300b04bb92ed328bb5cbd0c82126d0b18556e5
    Image:         registry.connect.redhat.com/cockroachdb/cockroach@sha256:0bd22d69db5ac570f30d3379afc67f6c2e46fc5b027c8aab42c3f562085d4672
    Image ID:      registry.connect.redhat.com/cockroachdb/cockroach@sha256:0bd22d69db5ac570f30d3379afc67f6c2e46fc5b027c8aab42c3f562085d4672
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      >- cp -p /cockroach/cockroach-certs-prestage/..data/* /cockroach/cockroach-certs/ && chmod 700 /cockroach/cockroach-certs/*.key && chown 1000581000:1000581000 /cockroach/cockroach-certs/*.key
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 16 Jul 2021 07:39:09 -0400
      Finished:     Fri, 16 Jul 2021 07:39:09 -0400
    Ready:          False
    Restart Count:  8
    Environment:    <none>
    Mounts:         <none>
...
```
