### ISSUE TITLE
Expose CRDB services via Ingress

### ISSUE THREAD

**Issue by abhishekdwivedi3060** [cockroachdb/cockroach-operator#712]
There should be a way for the user to expose CRDB services to the internet via Ingress

**Comment by abhishekdwivedi3060** [comment]
Initial thoughts around the API on how to enable ingress resource for suer.

**Comment by udnay** [comment]
I think we need an additional parameter for which ports to expose.

How is this defined in the helm-chart?

**Comment by abhishekdwivedi3060** [comment]
I believe port input won't be required here for ingress as we are already taking different port input in the spec like `GRPCPort`, `HTTPPort` and  `SQLPort`. Those port values can be directly used here based on service type to expose.

This is how we take input in helm-chart
```
ingress:
  enabled: true
  labels: {}
  annotations: {}
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: letsencrypt
  paths: [/]
  hosts: []
  # - cockroachlabs.com
  tls: []
  # - hosts: [cockroachlabs.com]
  #   secretName: cockroachlabs-tls
```
