### ISSUE TITLE
Network Policy Management

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#75]
@johnrk the helm chart creates network policies API definitions as well as manages cockroachdb clusters.  Is this a requirement?

https://github.com/cockroachdb/helm-charts/blob/25e4598e13fa9402242d837e828a550a20e8a648/cockroachdb/values.yaml#L357

```yaml
networkPolicy:
  enabled: false

  ingress:
    # List of sources which should be able to access the CockroachDB Pods via
    # gRPC port. Items in this list are combined using a logical OR operation.
    # Rules for allowing inter-communication are applied automatically.
    # If empty, then connections from any Pod is allowed.
    grpc: []
      # - podSelector:
      #     matchLabels:
      #       app.kubernetes.io/name: my-app-django
      #       app.kubernetes.io/instance: my-app

    # List of sources which should be able to access the CockroachDB Pods via
    # HTTP port. Items in this list are combined using a logical OR operation.
    # If empty, then connections from any Pod is allowed.
    http: []
      # - namespaceSelector:
      #     matchLabels:
      #       project: my-project
```
