### ISSUE TITLE
Ingress for Database

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#76]
The helm chart supports the creations of an ingress object.  Do we support this in the operator

```yaml
# CockroachDB's ingress for web ui.
ingress:
  enabled: false
  labels: {}
  annotations: {}
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: letsencrypt
  paths: [/]
  hosts: []
  # - cockroachlabs.com
  tls: []
  # - hosts: [cockroachlabs.com]
  #   secretName: cockroachlabs-tls
```

https://github.com/cockroachdb/helm-charts/blob/25e4598e13fa9402242d837e828a550a20e8a648/cockroachdb/values.yaml#L245
