### ISSUE TITLE
Add image API values

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#77]
Need to add the following API values

```yaml
image:
  pullPolicy: IfNotPresent
  credentials:
    registry: docker.io
    username: john_doe
    password: changeme
```
