### ISSUE TITLE
Add API values for site wide MetaData fields

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#78]
Need to add the following API values.  

```yaml
# Additional labels to apply to all Kubernetes resources created by this chart.
labels:
  app.kubernetes.io/part-of: my-app
annotations:
  foo/k8s.io: bar

# Cluster's default DNS domain.
# You should overwrite it if you're using a different one,
# otherwise CockroachDB nodes discovery won't work.
clusterDomain: cluster.local
```

Do we need to add API values for annotations?
