### ISSUE TITLE
cockroachdb-vcheck pod inherits resource limits and requests from cluster nodes

### ISSUE THREAD

**Issue by antonioua** [cockroachdb/cockroach-operator#796]
We faced an issue during cluster upgrade when `cockroachdb-vcheck` pod stuck in `Pending` state:

```
NAME                                                              READY   STATUS    RESTARTS   AGE
cockroach-operator-58996d89f9-xqlzn                               1/1     Running   1          14h
cockroachdb-0                                                     1/1     Running   0          8d
cockroachdb-1                                                     1/1     Running   0          8d
cockroachdb-2                                                     1/1     Running   0          8d
cockroachdb-vcheck-27248336-4tdpj                                 0/1     Pending   0          100
```

The describe shows that it got Resource Limits and Requests set to the values which was defined for cluster nodes in Custom Resource:

```
$ kubectl describe po cockroachdb-vcheck-27248332-ncb4k

...
    Limits:
      cpu:     6
      memory:  24Gi
    Requests:
      cpu:        4
      memory:     24Gi
    Environment:  <none>
    Mounts:       <none>
Conditions:
  Type           Status
  PodScheduled   False
Volumes:         <none>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     dedicated=redis:NoSchedule
                 dedicated=redis:NoExecute
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 600s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 600s

Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  55s (x3 over 2m3s)  default-scheduler  0/23 nodes are available: 2 node(s) had taint {dedicated: alb}, that the pod didn't tolerate, 2 node(s) had taint {dedicated: links-varnish}, that the pod didn't tolerate, 2 node(s) had taint {dedicated: links}, that the pod didn't tolerate, 2 node(s) had taint {dedicated: location}, that the pod didn't tolerate, 2 node(s) had taint {dedicated: varnish}, that the pod didn't tolerate, 4 node(s) had taint {dedicated: edge}, that the pod didn't tolerate, 5 Insufficient memory, 9 Insufficient cpu.
```

Due to this fact and lack of one more big worker node in our k8s cluster we can't perform cluster upgrade.

Here is our `CrdbCluster` resource configuration:

```
image:
  pullSecret: icm-coreeng-pull-secret
nodeSelector:
  dedicated: redis
nodes: 3
persistence:
  accessModes:
  - ReadWriteOnce
  enabled: true
  storage: 20Gi
  storageClassName: ibmc-block-bronze
  volumeMode: Filesystem
resources:
  limits:
    cpu: "6"
    memory: 24Gi
  requests:
    cpu: "4"
    memory: 24Gi
tlsEnabled: true
tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Equal
  value: redis
- effect: NoExecute
  key: dedicated
  operator: Equal
  value: redis
```

Does the `cockroachdb-vcheck` require the same Resource Requests as cluster nodes or it should run with less resources and this is a bug?

```
k8s v1.22.2
cockroachdb-operator:v2.3.0
cockroach:v21.1.10
```
