### ISSUE TITLE
Using cockroachDBVersion causes crash loop in the manager pod

### ISSUE THREAD

**Issue by pseudomuto** [cockroachdb/cockroach-operator#846]
If you set cockroachDBVersion, rather than a specific image, something goes horribly wrong. The idea is that if this field is set, we bypass the version checker job and instead validate against the environment variables for the manager. However, that isn't what's happening at the moment. We validate against the ENV as expected, but then continue to queue the version checker job, which panics on a nil pointer (see logs below).

My gut tells me we're missing an early return [here](https://github.com/cockroachdb/cockroach-operator/blob/c4da44293af3a976611d134cd9c2a6f9b2362df2/pkg/actor/validate_version.go#L80).

We'll need to add a regression test for this once fixed, maybe another test cases in one of the e2e tests would suffice.

**Steps to reproduce**

Add the following env var to the manager deployment (separate issue we need to address):

```
# config/manager/deployment.yaml
...
# added to cockroach-operator container
env:
  ...
  - name: RELATED_IMAGE_COCKROACH_v21_2_3
    value: cockroachdb/cockroach:v21.2.3
...
```

Start a local cluster via `make dev/up`. Verify that the manager is up and running by checking the pod logs. You should see something like this:

```
{"level":"info","ts":1643225333.6226966,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting workers","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","worker count":1}
```

Create a new crdb resource using the file below

```yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "60Gi"
        volumeMode: Filesystem
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2
      memory: 8Gi
  tlsEnabled: true
  cockroachDBVersion: v21.2.3
  nodes: 3
```

Notice that the manager is now crash looping due to a NPE. This is happening inside `Jobbuilder.MakeContainers`, which isn't supposed to be used when specifying the image via `cockroachDBVersion`.

```
E0126 19:30:29.709628       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 206 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1676000, 0x273d1b0})
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000136920})
        external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1676000, 0x273d1b0})
        GOROOT/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach-operator/pkg/resource.JobBuilder.MakeContainers({0xc00086c540, 0xc0004ccb10, {0xc0007204c0, 0x280}})
        pkg/resource/job.go:133 +0x5cc
github.com/cockroachdb/cockroach-operator/pkg/resource.JobBuilder.buildPodTemplate({_, _, {_, _}})
        pkg/resource/job.go:94 +0x105
github.com/cockroachdb/cockroach-operator/pkg/resource.JobBuilder.Build({0xc00086c540, 0xc0004ccb10, {0xc0007204c0, 0x46c558}}, {0x1afc148, 0xc00043ed80})
        pkg/resource/job.go:69 +0x1af
github.com/cockroachdb/cockroach-operator/pkg/resource.Reconciler.CompleteBuild({{{{0x1a7f520, 0xc0004cc4e0}, {0x1a7f540, 0xc000526840}}, 0xc0004cc600}, {0x1aa8dc8, 0xc000808ae0}, {0x1afac70,
 0xc00007e580}, 0xc0003e4930}, ...)
        pkg/resource/resource.go:101 +0x57
```

If you change your manifest to specify an image rather than cockroachDBVersion, you will not be able to apply your changes! Once this happens, your CR is stuck in this bad state. This is because the operator (manager) begins crash looping, which means the web hooks are not available, therefore no updates can be applied (like using a specific image for example). Once here, you don't have many options. 

> NOTE: If you _HAD_ to get it back and running, we did manage to set the failurePolicy on webhooks to `Ignore`, scale the operator deployment down, apply the change, scale the deployment back up, and set policy back to `Fail` for all hooks. This brought the CrdbCluster resource back into a good state.
