### ISSUE TITLE
When creating a cluster the clusterstatus indicates 'failed', but the cluster successfully started. 

### ISSUE THREAD

**Issue by carlsongould** [cockroachdb/cockroach-operator#951]
## Summary
**Partner Involved:** SpectroCloud 
Operator cluster status is showing the cluster as failed, but the cluster is online and available. 
 I have a partner that is trying to programmatically check the state of a  cluster created by our operator.

When running: `kubectl get CrdbCluster -o json`   to review the '`status`' and '`condition` '
 of the deployed CRDB cluster, the `clusterStatus` is listed as "Failed".  However, the cluster is available. I can connect and run DDL,DML statements.   The partner is seeing the same behavior. 

## Steps to reproduce
**My actions/env:**
1. Start Minikube
2. Install the operator  [docs](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-with-kubernetes.html#install-the-operator).
3.  Initialize the cluster following our [docs](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-with-kubernetes.html?#initialize-the-cluster).

## Expected Result
The expected result is when running the following command the `clusterStatus` is listed as 'running' and cluster is online and available.   
 Command: `kubectl get CrdbCluster -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{"status="}{.status.clusterStatus}{"\n"}{end}'`

## Actual Result
After running the command: `kubectl get CrdbCluster -o=jsonpath='{range .items[*]}{.metadata.name}{"\t"}{"status="}{.status.clusterStatus}{"\n"}{end}'` that the `clusterStatus` is in a `cockroachdb	status=Failed` state but the cluster is available.

Here are the logs: 
[cockroach-operator-manager-7db5d587b7-qlxws.log](https://github.com/cockroachdb/cockroach-operator/files/10415246/cockroach-operator-manager-7db5d587b7-qlxws.log)

**Comment by maitredede** [comment]
Hi, may it be related to #968 ?

**Comment by udnay** [comment]
@prafull01 can you take a look?

**Comment by prafull01** [comment]
RCA:

The issue is once the version checker returns the "job changed" not ready error, it marks the CR in Failed state temporary. Once the version checker job started and passes, the controller starts to add proper conditions however clusterStatus remains in the failed state only even after cluster is successfully started.

```
status:
    clusterStatus: Failed
    conditions:
    - lastTransitionTime: "2023-04-17T18:28:10Z"
      status: "False"
      type: Initialized
    - lastTransitionTime: "2023-04-17T18:28:25Z"
      status: "True"
      type: CrdbVersionChecked
    crdbcontainerimage: cockroachdb/cockroach:v22.2.7
    operatorActions:
    - lastTransitionTime: "2023-04-17T18:28:23Z"
      message: failed to check the version of the cluster
      status: Failed
      type: VersionCheckerAction
    version: v22.2.7
``` 

This happens because when the cluster creation finishes, the new `conditions` and `clusterStatus` is to be updated by the controller, the following error is generated by the client update operation:

```
,"error":"Operation cannot be fulfilled on crdbclusters.crdb.cockroachlabs.com \"cockroachdb\": the object has been modified; please apply your changes to the latest version and try again","
```
It happens because we fetched the resource and stored it in a variable in our reconcile. Then after a while, we try to update this resource using the data stored in the variable/controller. However, the state of the resource on the cluster changed from when we fetched the data using the client until when we try to update it.

Fix:

We can fix it by two ways:

1. Use the `r.client.Status().Patch()` operation which generates the patch between your changes and just apply that patch. 
2. Get the latest object again and then in that latest object set the status generated by reconcile logic and then call the update.

I am in favour of 1st way so I am raising PR with that change.
