### ISSUE TITLE
Self hosted CA breaks readinessProbe

### ISSUE THREAD

**Issue by japtain-cack** [cockroachdb/cockroach-operator#967]
# Environment
- Kubernetes v1.23.6
- Traefik ingress controller
- Longhorn storage controller
- Hashicorp Vault
- External Secrets Operator for short lived secrets obtained from vault k/v store
- Cert Manager for short lived certs obtained from vault pki store
- CRDB v2.10.0 Operator using TLS certs and secrets provided by vault, external-secrets-operator, and cert-manager
- Kustomize
- Terraform

# Issue overview
When using vault to provide TLS certs, to a secure CRDB cluster, the CA cannot be validated by the readinessProbe and fails with `Readiness probe failed: HTTP probe failed with statuscode: 503`. This results in pods continually restarting. I tried modifying the crdb statefulSet's `readinessProbe.httpGet.scheme`, and setting it to HTTP, but it is immediately set back to `HTTPS`.

I confirmed that the `/health?ready=1` endpoint works over HTTP by logging onto the crdb pod container and running `curl http://localhost:8080/health?ready=1`. A successful response was returned.

```
curl https://localhost:8080/health?ready=1 -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
```
curl http://localhost:8080/health?ready=1 -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /health?ready=1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Content-Type: application/json
< Grpc-Metadata-Content-Type: application/grpc
< Vary: Accept-Encoding
< Date: Mon, 13 Mar 2023 06:22:06 GMT
< Content-Length: 4
<
{

* Connection #0 to host localhost left intact
}
```

How, and where, can I define a patch/override to the readinessProbe scheme, and set this to `HTTP`? Maybe there is a better way to solve this issue? 

# Resources and files
### Certs
See kustomize below `cockroachdb/kustomize/certificates.yaml`

### Kustomize
```
### cockroachdb/kustomize/cockroachdb.yaml ###
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  # this translates to the name of the statefulset that is created
  name: cockroachdb
  namespace: cockroachdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "20Gi"
        volumeMode: Filesystem
        storageClassName: longhorn-ssd-backedup
    supportsAutoResize: false
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  tlsEnabled: true
  nodeTLSSecret: cockroachdb-node-tls
  clientTLSSecret: cockroachdb-client-tls
  image:
    name: cockroachdb/cockroach:v22.1.11
  # nodes refers to the number of crdb pods that are created
  # via the statefulset
  nodes: 3
  additionalLabels:
    crdb: is-cool
  # affinity is a new API field that is behind a feature gate that is
  # disabled by default.  To enable please see the operator.yaml file.

  # The affinity field will accept any podSpec affinity rule.
  #affinity:
  #  nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: kubernetes.io/arch
  #             operator: In
  #             values:
  #             - amd64

  # nodeSelectors used to match against
  nodeSelector:
    kubernetes.io/arch: amd64


### cockroachdb/kustomize/kustomization.yaml ###
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/cockroachdb/cockroach-operator/v2.10.0/install/crds.yaml
  - certificates.yaml
  - public-service.yaml
  - https://raw.githubusercontent.com/cockroachdb/cockroach-operator/v2.10.0/install/operator.yaml
  - cockroachdb.yaml
  #- client.yaml

patchesStrategicMerge:
  - operator.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -feature-gates
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: TolerationRules=true,AffinityRules=true
    target:
      kind: Deployment
      name: cockroach-operator-manager
      namespace: cockroach-operator-system


### cockroachdb/kustomize/certificates.yaml ###
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cockroachdb-node-tls
  namespace: cockroachdb
spec:
  secretName: cockroachdb-node-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: crdb.example.com
  dnsNames:
  - crdb.example.com
  - cockroachdb.example.com
  - cockroachdb.cockroachdb.svc.cluster.local
  - cockroachdb-0.cockroachdb.cockroachdb
  - cockroachdb-1.cockroachdb.cockroachdb
  - cockroachdb-2.cockroachdb.cockroachdb
  - "*.cockroachdb"
  - "*.cockroachdb.cockroachdb"
  - "*.cockroachdb.svc"
  - "*.cockroachdb.svc.cluster.local"
  - "node"
  - "localhost"
  - "cockroachdb-public"
  privateKey:
    algorithm: Ed25519
    encoding: PKCS8
    rotationPolicy: Always
    #size: 8192
    size: 2048
  encodeUsagesInRequest: true
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cockroachdb-client-tls
  namespace: cockroachdb
spec:
  secretName: cockroachdb-client-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: root.cockroachdb.cockroachdb.svc.cluster.local
  dnsNames:
  - "root"
  - "localhost"
  privateKey:
    algorithm: Ed25519
    encoding: PKCS8
    rotationPolicy: Always
    #size: 8192
    size: 2048
  encodeUsagesInRequest: true
  usages:
    - client auth
    - digital signature
    - key encipherment


### cockroachdb/kustomize/client.yaml ###
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure
  namespace: cockroachdb
spec:
  serviceAccountName: cockroachdb-sa
  containers:
  - name: cockroachdb-client-secure
    image: cockroachdb/cockroach:v22.1.8
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach/cockroach-certs/
    command:
    - sleep
    - "2147483648" # 2^31
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    projected:
        sources:
          - secret:
              name: cockroachdb-client-tls
              items:
                - key: ca.crt
                  path: ca.crt
          - secret:
              name: cockroachdb-client-tls
              items:
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
        defaultMode: 256
  nodeSelector:
    kubernetes.io/arch: amd64


### cockroachdb/kustomize/operator.yaml ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroach-operator-manager
  namespace: cockroach-operator-system
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64


### cockroachdb/kustomize/public-service.yaml ###
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-public
  namespace: cockroach-operator-system
spec:
  type: ExternalName
  externalName: cockroachdb-public.cockroachdb.svc.cluster.local
```

Hashicorp Vault (PKI configuration and details)
```
### vault/terraform/pki-server-certs.tf ###
#resource "vault_pki_secret_backend_cert" "concourse-tls" {
#  depends_on = [vault_pki_secret_backend_role.example-com-intermediate]
#
#  backend = vault_mount.pki-example-com-intermediate.path
#  name = vault_pki_secret_backend_role.example-com-intermediate.name
#
#  revoke                = true
#  common_name           = "ci.example.com"
#  auto_renew            = true
#  min_seconds_remaining = 604800
#  private_key_format    = "pkcs8"
#  ttl                   = 2592000
#  uri_sans              = [
#                            "concourse.concourse.svc.cluster.local",
#                            "*.concourse.svc.cluster.local",
#                            "ci.example.com",
#                          ]
#  alt_names             = [
#                            "DNS.1  = concourse",
#                            "DNS.2  = concourse.concourse",
#                            "DNS.3  = concourse.concourse.svc",
#                            "DNS.4  = *.concourse",
#                            "DNS.5  = *.concourse.svc",
#                          ]
#}
#
#resource "vault_pki_secret_backend_cert" "cockroachdb-tls" {
#  depends_on = [vault_pki_secret_backend_role.example-com-intermediate]
#
#  backend = vault_mount.pki-example-com-intermediate.path
#  name = vault_pki_secret_backend_role.example-com-intermediate.name
#
#  revoke                = true
#  common_name           = "crdb.example.com"
#  auto_renew            = true
#  min_seconds_remaining = 604800
#  private_key_format    = "pkcs8"
#  ttl                   = 2592000
#  uri_sans              = [
#                            "cockroachdb.cockroachdb.svc.cluster.local",
#                            "*.cockroachdb.svc.cluster.local",
#                            "cockroachdb.example.com",
#                            "crdb.example.com",
#                          ]
#  alt_names             = [
#                            "DNS.1  = cockroachdb",
#                            "DNS.2  = cockroachdb.cockroachdb",
#                            "DNS.3  = cockroachdb.cockroachdb.svc",
#                            "DNS.4  = *.cockroachdb",
#                            "DNS.5  = *.cockroachdb.svc",
#                          ]
#}


### vault/terraform/pki-root.tf ###
resource "vault_mount" "pki-example-com-root" {
  path                      = "example-com-root"
  type                      = "pki"
  description               = "PKI secrets engine"
  default_lease_ttl_seconds = 31557600 # 1 Year
  max_lease_ttl_seconds     = 315576000 # 10 Years
}

resource "vault_pki_secret_backend_root_cert" "example-com-root" {
  depends_on            = [vault_mount.pki-example-com-root]
  backend               = vault_mount.pki-example-com-root.path
  type                  = "internal"
  #lease_name            = "example.com-root-2022"
  common_name           = "example.com root ca"
  ttl                   = "315576000" # 10 years
  format                = "pem"
  private_key_format    = "pkcs8"
  key_type              = "ed25519"
  exclude_cn_from_sans  = true
  organization          = "example.com"
  country               = "USA"
  uri_sans              = [
                            "example.com",
                            "*.cluster.local",
                            "*.example.com",
                          ]
}

resource "vault_pki_secret_backend_role" "example-com-root" {
  backend                     = vault_mount.pki-example-com-root.path
  name                        = "example.com"
  ttl                         = 31557600 # 1 year
  max_ttl                     = 315576000 # 10 years
  key_type                    = "ed25519"
  #signature_bits              = 0
  allow_any_name              = false
  allow_ip_sans               = false
  allowed_domains             = ["example.com", "cluster.local"]
  allow_subdomains            = true
  allow_localhost             = false
  allow_bare_domains          = true
  allow_glob_domains          = true
  server_flag                 = true
  #allow_wildcard_certificates = true
  enforce_hostnames           = true
  organization                = ["example.com"]
  country                     = ["USA"]
  require_cn                  = true
  allowed_uri_sans            = [
                                  "example.com",
                                  "*.example.com",
                                ]
}

resource "vault_pki_secret_backend_config_urls" "example-com-root" {
  backend = vault_mount.pki-example-com-root.path
  issuing_certificates      = ["https://vault.example.com/v1/example-com-root/ca"]
  crl_distribution_points   = ["https://vault.example.com/v1/example-com-root/crl"]
}

resource "vault_pki_secret_backend_crl_config" "example-com-root-crl" {
  backend = vault_mount.pki-example-com-root.path
  expiry  = "24h"
  disable = false
}


### vault/terraform/pki-intermediate.tf ###
resource "vault_mount" "pki-example-com-intermediate" {
  path                      = "example-com-intermediate"
  type                      = "pki"
  description               = "PKI secrets engine"
  default_lease_ttl_seconds = 63115200 # 2 years
  max_lease_ttl_seconds     = 157788000 # 5 Years
}

resource "vault_pki_secret_backend_intermediate_cert_request" "example-com-intermediate" {
  depends_on                = [vault_mount.pki-example-com-intermediate]
  backend                   = vault_mount.pki-example-com-intermediate.path
  type                      = "internal"
  #lease_name                = "example.com-intermediate-2022"
  common_name               = "example.com intermediate ca"
  format                    = "pem"
  private_key_format        = "pkcs8"
  key_type                  = "ed25519"
  exclude_cn_from_sans      = true
  organization              = "example.com"
  country                   = "USA"
  uri_sans                  = [
                                "example.com",
                                "*.example.com",
                              ]

}

resource "vault_pki_secret_backend_root_sign_intermediate" "example-com-intermediate" {
  depends_on            = [vault_pki_secret_backend_intermediate_cert_request.example-com-intermediate]
  backend               = vault_mount.pki-example-com-root.path
  csr                   = vault_pki_secret_backend_intermediate_cert_request.example-com-intermediate.csr
  use_csr_values        = true
  common_name           = "example.com intermediate ca"
  format                = "pem_bundle"
  ttl                   = 157788000 # 5 Years
  exclude_cn_from_sans  = true
  #permitted_dns_domains = ["example.com", "cluster.local"]
  revoke                = true
}

resource "vault_pki_secret_backend_intermediate_set_signed" "example-com-intermediate" {
  backend     = vault_mount.pki-example-com-intermediate.path
  certificate = vault_pki_secret_backend_root_sign_intermediate.example-com-intermediate.certificate
}

resource "vault_pki_secret_backend_role" "example-com-intermediate" {
  backend                     = vault_mount.pki-example-com-intermediate.path
  name                        = "example.com"
  #ttl                         = 2592000 # 30 days
  ttl                         = 86400 # 1 day
  #max_ttl                     = 31557600 # 1 year
  max_ttl                         = 86400 # 1 day
  key_type                    = "ed25519"
  #signature_bits              = 0
  allow_any_name              = true
  allow_ip_sans               = true
  #allowed_domains             = ["example.com", "cluster.local"]
  allow_subdomains            = true
  allow_localhost             = true
  allow_bare_domains          = true
  allow_glob_domains          = true
  server_flag                 = true
  #allow_wildcard_certificates = true
  enforce_hostnames           = false
  organization                = ["example.com"]
  country                     = ["USA"]
  require_cn                  = true
  #key_usage                   = ["DigitalSignature", "KeyAgreement", "KeyEncipherment"]
  #ext_key_usage               = ["ServerAuth", "ClientAuth"]
  #allowed_uri_sans            = [
  #                                "example.com",
  #                                "*.example.com",
  #                              ]
}

resource "vault_pki_secret_backend_config_urls" "example-com-intermediate" {
  backend = vault_mount.pki-example-com-intermediate.path
  issuing_certificates      = ["https://vault.example.com/v1/example-com-intermediate/ca"]
  crl_distribution_points   = ["https://vault.example.com/v1/example-com-intermediate/crl"]
}

resource "vault_pki_secret_backend_crl_config" "example-com-intermediate-crl" {
  backend = vault_mount.pki-example-com-intermediate.path
  expiry  = "24h"
  disable = false
}
```
