### ISSUE TITLE
Kind: CRDB ingress isn't working

### ISSUE THREAD

**Issue by simonebenati** [cockroachdb/cockroach-operator#996]
Hello,

My goal is to expose cockroachdb to outside the k8s cluster and according to the documentation the only relevant thing I found was this:
I configured this part in the crdb correct section

```
   ingress:
     ui:
       ingressClassName: haproxy
       annotations:
       key: value
       host: test.stage.com
    sql:
      ingressClassName: haproxy
      annotations:
        key: value
       host: cockroachdb.dev-service-stage.k8s.mi1.prod.cloudfire.it
```
The ingress is spawned accordingly but it doesn't take on any configuration nor ip and therefore the address isn't reachable. I have no idea on how to debug this further, could anyone provide more informations/details or how to proceed?
The dns record is resolved correctly if I ping it besides that I don't know how to proceed.
